:root{--bg:#f4f7fb;--surface:#fff;--surface2:#f8fafc;--text:#182033;--muted:#6a7484;--line:#e4e9f0;--primary:#315efb;--primary2:#2448d0;--danger:#c23b3b;--shadow:0 12px 30px rgba(25,40,70,.08)}
body.dark{--bg:#11161e;--surface:#1b222d;--surface2:#151b24;--text:#eef3f8;--muted:#9eabbc;--line:#2a3442;--shadow:0 12px 30px rgba(0,0,0,.28)}
*{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--text)}button,input,select{font:inherit}button{cursor:pointer}.hidden{display:none!important}
.login-screen{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(430px,100%);background:var(--surface);border:1px solid var(--line);border-radius:22px;padding:32px;box-shadow:var(--shadow)}.logo{width:46px;height:46px;border-radius:12px;background:var(--primary);color:#fff;display:grid;place-items:center;font-weight:800}.login-card h1{margin:16px 0 5px;font-size:27px}.login-card p,.login-card small{color:var(--muted)}form{display:grid;gap:14px;margin-top:18px}label{display:grid;gap:7px;font-size:13px;font-weight:700}input,select{width:100%;border:1px solid var(--line);background:var(--surface2);color:var(--text);padding:11px 12px;border-radius:10px;outline:none}input:focus,select:focus{border-color:var(--primary);box-shadow:0 0 0 3px rgba(49,94,251,.1)}
.app{min-height:100vh;display:grid;grid-template-columns:250px 1fr}.sidebar{background:var(--surface);border-right:1px solid var(--line);padding:20px 15px;display:flex;flex-direction:column}.brand{display:flex;gap:10px;align-items:center;padding:4px 10px 24px}.brand small{display:block;color:var(--muted);font-size:11px}.sidebar nav{display:grid;gap:5px}.nav{border:0;background:transparent;color:var(--muted);text-align:left;padding:12px;border-radius:11px}.nav:hover{background:var(--surface2);color:var(--text)}.nav.active{background:rgba(49,94,251,.1);color:var(--primary);font-weight:700}.bottom-nav{margin-top:auto;display:grid;gap:5px}.danger{color:var(--danger)}
.main{min-width:0}.topbar{height:76px;padding:14px 28px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;background:var(--surface)}.topbar small{color:var(--muted)}.topbar h2{margin:2px 0 0;font-size:22px}.chip{padding:8px 12px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:13px}.mobile{display:none;background:transparent;border:0;font-size:20px;color:var(--text)}
.view{display:none;padding:28px;max-width:1500px;margin:auto}.active-view{display:block}.head{display:flex;justify-content:space-between;gap:15px;margin-bottom:20px}.head h3{margin:0 0 5px;font-size:25px}.head p,.panel p{margin:0;color:var(--muted)}.btn{border:1px solid transparent;border-radius:10px;padding:10px 14px;font-weight:700}.primary{background:var(--primary);color:#fff}.primary:hover{background:var(--primary2)}.secondary{background:var(--surface);border-color:var(--line);color:var(--text)}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.card,.panel{background:var(--surface);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow)}.card{padding:18px}.card span{color:var(--muted);font-size:13px}.card strong{display:block;margin-top:5px;font-size:28px}.grid2{display:grid;grid-template-columns:2fr 1fr;gap:15px;margin-top:15px}.panel{padding:18px}.panel h3{margin-top:0}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:600px}th,td{padding:12px 10px;border-bottom:1px solid var(--line);text-align:left;font-size:13px}th{color:var(--muted);background:var(--surface2)}tbody tr:hover{background:var(--surface2)}
.quick{width:100%;padding:12px;border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:11px;text-align:left;margin-bottom:8px}.quick:hover{border-color:var(--primary)}.quick small{display:block;color:var(--muted);margin-left:25px}.quick b{margin-left:7px}.toolbar{display:flex;gap:10px;margin-bottom:14px}.toolbar input{max-width:540px}.form-panel{max-width:900px}.form{grid-template-columns:1fr 1fr}.actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:10px}.mini{padding:7px 9px;border:1px solid var(--line);background:var(--surface);border-radius:8px}.summary{margin:14px 0;padding:14px;border:1px solid var(--line);border-radius:10px;background:var(--surface2)}.empty{text-align:center;color:var(--muted);padding:28px}.toast{position:fixed;right:20px;bottom:20px;background:#172033;color:#fff;padding:12px 15px;border-radius:10px;opacity:0;transform:translateY(10px);transition:.2s}.toast.show{opacity:1;transform:none}
@media(max-width:1000px){.stats{grid-template-columns:repeat(2,1fr)}.grid2{grid-template-columns:1fr}}@media(max-width:800px){.app{grid-template-columns:1fr}.sidebar{position:fixed;z-index:10;inset:0 auto 0 0;width:250px;transform:translateX(-100%);transition:.2s}.sidebar.open{transform:none}.mobile{display:block}.topbar{padding:14px 18px}.view{padding:20px 18px}}@media(max-width:620px){.stats,.form{grid-template-columns:1fr}.head{flex-direction:column}.toolbar{flex-direction:column}.actions{justify-content:stretch}.actions .btn{flex:1}}
